//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EN
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class enEntities : DbContext
    {
        public enEntities()
            : base("name=enEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cours> courses { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<book> books { get; set; }
        public virtual DbSet<course_attendance> course_attendance { get; set; }
        public virtual DbSet<chatboot> chatboots { get; set; }
        public virtual DbSet<contact> contacts { get; set; }
        public virtual DbSet<deafcours> deafcourses { get; set; }
    }
}
